version: '2'

services:
  mongodb:
    image: mongo:latest
    ports:
        - 27020:27017
    expose: [27017]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin-user
      - MONGO_INITDB_ROOT_PASSWORD=admin-password
      - MONGO_INITDB_DATABASE=admin
    
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  restore:
    image: mongo
    volumes:
      - ./db/bson:/var/dump
    links:
      - mongodb:mongodb
      
    command: mongorestore --host mongodb:27017 -d lotr --verbose /var/dump

  app:
    image: node
    environment:
        - PORT=3000
        - DATABASE_URL=mongodb://admin:password@mongodb:27017/lotr
        - NODE_ENV=production
    ports:
        - 3000:3000
  
    volumes:
         - ./backend/:/var/www/public_html/lotr-api/
  
    working_dir: /var/www/public_html/lotr-api/
  
    command: bash -c "npm install && npm run prod" 
  
    